### ISSUE TITLE
请求中多次被用到的基础类型 的 类问题如何解决？

### ISSUE THREAD

**Issue by helpcode** [zquancai/class-converter#15]
实际项目中，比如接口的请求 分页这些会多次用到。

原项目情况如下

公共 分页查询数据的类型
<img width="560" alt="image" src="https://github.com/zquancai/class-converter/assets/17229604/7880b577-d953-4a5d-8d28-9e87e0958dfc">

A页面的某个请求用到如下：
<img width="1394" alt="image" src="https://github.com/zquancai/class-converter/assets/17229604/ccc482b3-ede2-45aa-ad9b-4d103d8d9b20">

B页面的某个请求用到如下：
<img width="1215" alt="image" src="https://github.com/zquancai/class-converter/assets/17229604/320d4534-59d4-4f97-96c3-0bade0b93c2d">

这种情况下用类来改写，公共类型 PaginationRes 改如何封装呢？PaginationRes 接口里面的 result 类型在不同方法中被调用，类型是不一样的。

没想明白，希望作者有时间能回复一下，谢谢

**Comment by zquancai** [comment]
class convert 其实不是 interface 的写法，是数据实例化是做的一次序列化操作，所以如果 result 数据不一样的话，建议用继承来实现：
```ts
class PaginationBase<T> {
  @property()
  next_page: number

  result: T
}

class User {
  @property()
  id: number

  @property()
  name: string
}

class PaginationUsersRes extends PaginationBase<Item[]> {
  @property()
  next_page: number

  @property(User)
  result: User[]
}

class Item {
  @property()
  id: number

  @property()
  name: string
}

class PaginationListRes extends PaginationListBase<Item[]> {
  @property()
  next_page: number

  @property(Item)
  result: Item[]
}
```

可以参考上面的例子
